config/routes.rb
Rails.application.routes.draw do
  resources :engage_states

  resources :questions

  resources :attachments

  resources :post_ratings

  resources :replies

  resources :posts

  root to: "posts#index"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

end

app/models/reply.rb
class Reply < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  # 빈 댓글 금지
  validates :content, presence: true
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  before_action :set_reply, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]

  respond_to :html

  def index
    @replies = Reply.all
    respond_with(@replies)
  end

  def show
    respond_with(@reply)
  end

  def new
    @reply = Reply.new
    respond_with(@reply)
  end

  def edit
  end

  def create
    @reply = Reply.new(reply_params)
    @reply.save
    redirect_to :back
  end

  def update
    @reply.update(reply_params)
    respond_with(@reply)
  end

  def destroy
    post_url = "/posts/#{@reply.post_id}"
    @reply.destroy
    respond_to do |format|
      format.html { redirect_to post_url, notice: '꼭... 하고 싶었던 얘긴 아녔어!' }
      format.json { head :no_content }
    end
  end

  private
    def set_reply
      @reply = Reply.find(params[:id])
    end

    def reply_params
      params.require(:reply).permit(:post_id, :user_id, :content)
    end
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/views/replies/_form.html.erb
<%= form_for(@reply) do |f| %>
  <% if @reply.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reply.errors.count, "error") %> prohibited this reply from being saved:</h2>

      <ul>
      <% @reply.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <input type="hidden" value=<%= @post.id %> name="reply[post_id]">
  <input type="hidden" value=<%= current_user.id %> name="reply[user_id]">

  <div class="input-group text-center">
    <input id="reply_content" class="form-control input-md" name="reply[content]" type="text" placeholder="하... 하고 싶은 말 있어?">
    <span class="input-group-btn">
      <button class="btn btn-default"><i class="glyphicon glyphicon-share"></i></button>
    </span>
  </div>

<% end %>

app/views/replies/edit.html.erb
<h1>Editing reply</h1>

<%= render 'form' %>

<%= link_to 'Show', @reply %> |
<%= link_to 'Back', replies_path %>

app/views/replies/index.html.erb
<h1>Listing replies</h1>

<table>
  <thead>
    <tr>
      <th>Post</th>
      <th>User</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @replies.each do |reply| %>
      <tr>
        <td><%= reply.post %></td>
        <td><%= reply.user %></td>
        <td><%= reply.content %></td>
        <td><%= link_to 'Show', reply %></td>
        <td><%= link_to 'Edit', edit_reply_path(reply) %></td>
        <td><%= link_to 'Destroy', reply, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reply', new_reply_path %>

app/views/replies/new.html.erb
<h1>New reply</h1>

<%= render 'form' %>

<%= link_to 'Back', replies_path %>

app/views/replies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @reply.post %>
</p>

<p>
  <strong>User:</strong>
  <%= @reply.user %>
</p>

<p>
  <strong>Content:</strong>
  <%= @reply.content %>
</p>

<%= link_to 'Edit', edit_reply_path(@reply) %> |
<%= link_to 'Back', replies_path %>