config/routes.rb
Rails.application.routes.draw do
  resources :engage_states

  resources :questions

  resources :attachments

  resources :post_ratings

  resources :replies

  resources :posts

  root to: "posts#index"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

end

app/models/engage_state.rb
class EngageState < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/controllers/engage_states_controller.rb
class EngageStatesController < ApplicationController
  before_action :set_engage_state, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @engage_states = EngageState.all
    respond_with(@engage_states)
  end

  def show
    respond_with(@engage_state)
  end

  def new
    @engage_state = EngageState.new
    respond_with(@engage_state)
  end

  def edit
    @engage_state.update(answer: params[:answer])
    if @engage_state.answer == @engage_state.post.questions.find_by(number: @engage_state.question_number).answer
      @engage_state.update(is_valid: true)
      next_question = @engage_state.post.questions.find_by(number: @engage_state.question_number + 1)
      if next_question.nil?
        @engage_state.post.update(is_complete: true, hunter: current_user)
        # redirect_to "/post_ratings/new"
      else
        next_engage_state = EngageState.new(user: current_user, post: @engage_state.post,
                                            question_number: @engage_state.question_number + 1, answer: "",
                                            is_valid: false)
        next_engage_state.save
        # redirect_to "/questions/#{next_question.id}"
      end
    else
      redirect_to :back
    end
  end

  def create
    @engage_state = EngageState.new(engage_state_params)

    # 답변의 유효성 확인
    answer = @engage_state.post.questions.find_by(number: @engage_state.question_number).answer
    if @engage_state.answer == answer
      @engage_state.is_valid = true
    else
      @engage_state.is_valid = false
    end

    @engage_state.save
    respond_with(@engage_state)
  end

  def update
    @engage_state.update(engage_state_params)
    respond_with(@engage_state)
  end

  def destroy
    @engage_state.destroy
    respond_with(@engage_state)
  end

  private
    def set_engage_state
      @engage_state = EngageState.find(params[:id])
    end

    def engage_state_params
      params.require(:engage_state).permit(:user_id, :post_id, :question_number)
    end
end

app/helpers/engage_states_helper.rb
module EngageStatesHelper
end

app/views/engage_states/_form.html.erb
<%= form_for(@engage_state) do |f| %>
  <% if @engage_state.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@engage_state.errors.count, "error") %> prohibited this engage_state from being saved:</h2>

      <ul>
      <% @engage_state.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <input type="hidden" value=<%= @post.id %> name="engage_state[post_id]">
  <input type="hidden" value=<%= current_user.id %> name="engage_state[user_id]">
  <input type="hidden" value=<%= @q_num %> name="engage_state[question_number]">

  <div class="input-group text-center">
    <input type="text" id="engage_state_answer" name="engage_state[answer]" class="form-control input-md">
    <span class="input-group-btn">
      <button class="btn btn-default"><i class="glyphicon glyphicon-heart"></i></button>
    </span>
  </div>
<% end %>

app/views/engage_states/edit.html.erb
<h1>Editing engage_state</h1>

<%= render 'form' %>

<%= link_to 'Show', @engage_state %> |
<%= link_to 'Back', engage_states_path %>

app/views/engage_states/index.html.erb
<h1>Listing engage_states</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Post</th>
      <th>Question number</th>
      <th>IsValid</th>
      <th>Answer</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @engage_states.each do |engage_state| %>
      <tr>
        <td><%= engage_state.user.id %></td>
        <td><%= engage_state.post.id %></td>
        <td><%= engage_state.question_number %></td>
        <td><%= engage_state.is_valid %></td>
        <td><%= engage_state.answer %></td>
        <td><%= link_to 'Show', engage_state %></td>
        <td><%= link_to 'Edit', edit_engage_state_path(engage_state) %></td>
        <td><%= link_to 'Destroy', engage_state, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Engage state', new_engage_state_path %>

app/views/engage_states/new.html.erb
<h1>New engage_state</h1>

<%= render 'form' %>

<%= link_to 'Back', engage_states_path %>

app/views/engage_states/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @engage_state.user %>
</p>

<p>
  <strong>Post:</strong>
  <%= @engage_state.post %>
</p>

<p>
  <strong>Question number:</strong>
  <%= @engage_state.question_number %>
</p>

<p>
  <strong>Question number:</strong>
  <%= @engage_state.is_valid %>
</p>

<p>
  <strong>Question number:</strong>
  <%= @engage_state.answer %>
</p>

<%= link_to 'Edit', edit_engage_state_path(@engage_state) %> |
<%= link_to 'Back', engage_states_path %>